import AdminDashboard from '@/components/layout/Admin'

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayoutAdmin({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <AdminDashboard>{children}</AdminDashboard>
}
